# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fib_basic(prev1, prev2, sumVal, maxVal):
    if prev1 > maxVal:
        return sumVal
    if prev1 % 2:
        sumVal += prev1
    return fib_basic(prev1 + prev2, prev1, sumVal, maxVal)


print(fib_basic(2, 1, 2, 4000000))

# solved: 4613732
